In [ ]:
# this is where you have to practise a lot okay up to you i am a fast paced self learner do pip install numpy if you havent already
import numpy as np
#we are importing a numpy module here this is important

#this will create an array this is not a list this is an array
a = np.array([1,2,3,4])

print(type(a))
#this is used to indentify the array or to prove its an array 

print(a.dtype) #this will return us the datatype of an element in an array unlike lists which are mixed this array supports only one data type 
print(a.shape) #this will return some thing like (4,) which tells us that this is a 1d array and has 4 elements 
print(a.ndim)# this will tell us which dimentional array is this 
print(a.size) #this will tell us how many elements are there 

print(a) # we are printing array

#arrays can be also done in this way
a = np.array([[[1],[2],[3]]]) #This is a 2d array unlike the above array
print(a)
print(a.shape) #this will return some thing like (3,1) which tells us that this is a 2d array and has 3 elements 


print(a[0][0].shape) # in this we are selecting the rows columns blocks careful with this if this was a 1d array you would hit an error instantly
# which feels like you are removing things but no you just viewing some part of the entire thing



<class 'numpy.ndarray'>
int64
(4,)
1
4
[1 2 3 4]
[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [ ]:

np.zeros(5,5,6) #this will take by default as a float
np.zeros((5,6,6),dtype=int) #this will create a 3d array filled with zeros and yes think of it as a dummy values
np.zeros((5,6,6),dtype=bool) #this will have either trues or falses initally its all false

np.ones(2,3) #this is similar to that of  zeros but instead of zeros we fill the thing with ones  default is also float so 1.1. type thing
np.ones((2,3),dtype=int) # this will do the thing with int 
np.ones((5,6,6),dtype=bool) #this is going to all trues by default


np.full((2,3),7) #this is similar to that of  zeros/ones but instead of zeros/ones we fill the thing with our value  default is also float so 1.1. type thing
np.full((2,3),8,dtype=int) # this will do the thing with int 
np.full((5,6,6),3,dtype=bool) #look if you use 0 "" false it will give false rest will go true


np.empty((2,3)) #this results in a array with garbage values you will see random floats
np.empty((2,3),dtype=int) # this will do the thing with int 
np.empty((5,6,6), dtype=bool) #depends on garbage value you wil see random true and falses

#this will create a unit matrx and it is by default a float and not a int and it has the following parameters
#np.eye(n,m,k,dtype) n,m is the size of martix here k is only 3 things 0 on the diagonal 1 above diagonal and -1 for below diagonal 
#you try since its easy not much for me to tell here
#if you put dtype as bool your 1s will be true and 0 will be false
np.eye(1,2,0,dtype=int)

#this is a faster version for the eye but for sq matrx of size nxn with n as the diagonal and dtype is the thing to declare the type no gimics here 
np.identity(8,dtype=int) 

#here the parameters are this np.diag([1,23,33],dtype=) its int by default this is for 1d array 
# Construct diagonal matrix:
np.diag([1, 2, 3])
# Output:
# [[1 0 0]
#  [0 2 0]
#  [0 0 3]]

# Extract diagonal from 2D matrix:
A = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
np.diag(A)
# Output: [1 5 9]


In [ ]:
# arange is simalar to that of pythons range we can do the same thing in here as well except the fact that we have one ore extra parameter
import numpy as np

np.arange(5)           # [0 1 2 3 4]
np.arange(1, 10, 2)    # [1 3 5 7 9]
np.arange(10, 1, -2,dtype=int)   # [10 8 6 4 2]
np.arange(0, 1, 0.2)   # [0.  0.2 0.4 0.6 0.8]
#here dtype depends on your input not like a set default 

#here line space we have start value stop value no_of values in between endpoint=true/false which is including the last value or keep it out and then the dtype which again depends on your input
#try the following to get an understanding of these
#np.logspace(start, stop, num=50, endpoint=True,  dtype=None)
np.linspace(0, 5)                   # 50 values from 0 to 5 (default num=50)
np.linspace(1, 10, 2)               # array([ 1., 10.]) → 2 values: start and stop
np.linspace(10, 1, 5, dtype=int, endpoint=True) #dtype first? endpoint first bruh they same but you cant change this start end howmany
np.linspace(10, 1, 5, endpoint=True, dtype=int)   # array([10, 8, 6, 4, 1]) → 5 values, descending, cast to int
np.linspace(0, 1, 6)                # array([0. , 0.2, 0.4, 0.6, 0.8, 1. ]) → step = 0.2 (approx)

#here you try and tell me 
#np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
#the values will be exponential the log may make you feel like its decreasing values no log space meaning exponential values
np.logspace(0, 5)               
np.logspace(1, 10, 2)              
np.logspace(10, 1, 5, dtype=int, endpoint=True) 
np.logspace(10, 1, 5, endpoint=True, dtype=int)   
np.logspace(0, 1, 6)


#use print statements to test these



array([ 1.        ,  1.58489319,  2.51188643,  3.98107171,  6.30957344,
       10.        ])

In [ ]:
#this is a randint it will generate a int values based on your given limit the size as you guessed will define the array size  no gimics here like the above
np.random.randint(1, 10, size=(3, 3))
#this will create a postive float values only from 0 to 1 and no non negatives nor the control option like above just raw size
np.random.rand(1,2,3)
#this will generate values based on standard devation 0 = mean 1 = sd and it will have  negative unlike the above and has no control over generation
np.random.randn(12,23) 

#this is same as the rand but it has much more control 
#np.random.uniform(startlimit,endlimit,size=(2,)) #more you add to size new dimention 
np.random.uniform(23,32,size=(12,23)) #this will generate a random generated float array with your limits
