In [ ]:
# this is where you have to practise a lot okay up to you i am a fast paced self learner do pip install numpy if you havent already
import numpy as np
#we are importing a numpy module here this is important

#this will create an array this is not a list this is an array
a = np.array([1,2,3,4])

print(type(a))
#this is used to indentify the array or to prove its an array 

print(a.dtype) #this will return us the datatype of an element in an array unlike lists which are mixed this array supports only one data type 
print(a.shape) #this will return some thing like (4,) which tells us that this is a 1d array and has 4 elements  in a row
print(a.ndim)# this will tell us which dimentional array is this 
print(a.size) #this will tell us how many elements are there 

#a.shape[0] will take row a.shape[1] will select the column for 2d arrays follow this order
#batch block row col

print(a) # we are printing array

#arrays can be also done in this way
a = np.array([[[1],[2],[3]]]) #This is a 2d array unlike the above array
print(a)
print(a.shape) #this will return some thing like (3,1) which tells us that this is a 2d array and has 3 elements 


print(a[0][0].shape) # in this we are selecting the rows columns blocks careful with this if this was a 1d array you would hit an error instantly
# which feels like you are removing things but no you just viewing some part of the entire thing



<class 'numpy.ndarray'>
int64
(4,)
1
4
[1 2 3 4]
[[[1]
  [2]
  [3]]]
(1, 3, 1)


In [ ]:

np.zeros(5,5,6) #this will take by default as a float
np.zeros((5,6,6),dtype=int) #this will create a 3d array filled with zeros and yes think of it as a dummy values
np.zeros((5,6,6),dtype=bool) #this will have either trues or falses initally its all false

np.ones(2,3) #this is similar to that of  zeros but instead of zeros we fill the thing with ones  default is also float so 1.1. type thing
np.ones((2,3),dtype=int) # this will do the thing with int 
np.ones((5,6,6),dtype=bool) #this is going to all trues by default


np.full((2,3),7) #this is similar to that of  zeros/ones but instead of zeros/ones we fill the thing with our value  default is also float so 1.1. type thing
np.full((2,3),8,dtype=int) # this will do the thing with int 
np.full((5,6,6),3,dtype=bool) #look if you use 0 "" false it will give false rest will go true


np.empty((2,3)) #this results in a array with garbage values you will see random floats
np.empty((2,3),dtype=int) # this will do the thing with int 
np.empty((5,6,6), dtype=bool) #depends on garbage value you wil see random true and falses

#this will create a unit matrx and it is by default a float and not a int and it has the following parameters
#np.eye(n,m,k,dtype) n,m is the size of martix here k is only 3 things 0 on the diagonal 1 above diagonal and -1 for below diagonal 
#you try since its easy not much for me to tell here
#if you put dtype as bool your 1s will be true and 0 will be false
np.eye(1,2,0,dtype=int)

#this is a faster version for the eye but for sq matrx of size nxn with n as the diagonal and dtype is the thing to declare the type no gimics here 
np.identity(8,dtype=int) 

#here the parameters are this np.diag([1,23,33],k=0,1,-1) its int by default this is for 1d array 
#like i said before k here has 0 on diag -1 below +1 above diag line 
# Construct diagonal matrix:
np.diag([1, 2, 3])
# Output:
# [[1 0 0]
#  [0 2 0]
#  [0 0 3]]

# Extract diagonal from 2D matrix:
A = np.array([[1,2,3], [4,5,6], [7,8,9]]) 
np.diag(A)
# Output: [1 5 9]


In [ ]:
# arange is simalar to that of pythons range we can do the same thing in here as well except the fact that we have one ore extra parameter
import numpy as np

np.arange(5)           # [0 1 2 3 4]
np.arange(1, 10, 2)    # [1 3 5 7 9]
np.arange(10, 1, -2,dtype=int)   # [10 8 6 4 2]
np.arange(0, 1, 0.2)   # [0.  0.2 0.4 0.6 0.8]
#here dtype depends on your input not like a set default 

#here line space we have start value stop value no_of values in between endpoint=true/false which is including the last value or keep it out and then the dtype which again depends on your input
#try the following to get an understanding of these
#np.logspace(start, stop, num=50, endpoint=True,  dtype=None)
np.linspace(0, 5)                   # 50 values from 0 to 5 (default num=50)
np.linspace(1, 10, 2)               # array([ 1., 10.]) → 2 values: start and stop
np.linspace(10, 1, 5, dtype=int, endpoint=True) #dtype first? endpoint first bruh they same but you cant change this start end howmany
np.linspace(10, 1, 5, endpoint=True, dtype=int)   # array([10, 8, 6, 4, 1]) → 5 values, descending, cast to int
np.linspace(0, 1, 6)                # array([0. , 0.2, 0.4, 0.6, 0.8, 1. ]) → step = 0.2 (approx)

#here you try and tell me 
#np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)
#the values will be exponential the log may make you feel like its decreasing values no log space meaning exponential values
np.logspace(0, 5)               
np.logspace(1, 10, 2)              
np.logspace(10, 1, 5, dtype=int, endpoint=True) 
np.logspace(10, 1, 5, endpoint=True, dtype=int)   
np.logspace(0, 1, 6)


#use print statements to test these



array([ 1.        ,  1.58489319,  2.51188643,  3.98107171,  6.30957344,
       10.        ])

In [ ]:
#this is a randint it will generate a int values based on your given limit the size as you guessed will define the array size  no gimics here like the above
np.random.randint(1, 10, size=(3, 3))
#this will create a postive float values only from 0 to 1 and no non negatives nor the control option like above just raw size
np.random.rand(1,2,3) 
np.random.random((1,3,4)) # this is same minor difference it takes input as tuples not as direclty why this exists this one is new and above is a dino legacy code
#this will generate values based on standard devation 0 = mean 1 = sd and it will have  negative unlike the above and has no control over generation
np.random.randn(12,23) 

#this is same as the rand but it has much more control 
#np.random.uniform(startlimit,endlimit,size=(2,)) #more you add to size new dimention 
np.random.uniform(23,32,size=(12,23)) #this will generate a random generated float array with your limits

#this will pick things for you if you spefify range or values size is the same 2d is also possible here 
#replace here means do i take the same thing again or not type false means no i dont true means i take the same thing again
#the first is choice you give int it takes values starting from 0 to that value and list it will pick only from list 

np.random.choice(5, size=3, replace=False)
# Picks 3 unique values from [0, 1, 2, 3, 4]

#this is us introducong probablity so to give some values much higher chances then other  the indexes are linked 0.1 and 10 like that 
#dont screw up the thing dont imagine ahh the probablity is auto mapped index of that checks index in this for probablity 
# in that p all that decimal should add up to 1 otherwise you face error 
np.random.choice([10, 20, 30], size=5, p=[0.1, 0.7, 0.2])
# Heavily biased towards 20

#this is the full complete syntax use case 
np.random.choice([1,2,3,4],size=(1,2),replace=True,p=[0.3,0.5,0.1,0.1])

#this will shuffle in random order for you and it wont modify the input you give and no extra parameters it will only work for any nd array 
#be aware that you will a real shuffle not in between the one row or column its full array run this 5 times you will understand
np.random.permutation([[23,23,32,89],[232,23,32,32]])

#this is going only work for 2d arrays and only does the rows suffle if you want column shuffle then you transpose the given matrix
#you will see that in matrix operations later

arr = np.array([[1, 2], [3, 4], [5, 6]])
np.random.shuffle(arr)
# arr is now row-shuffled version

a = [[1,2,3,5,4]]
a.reshape(1,3)
#this will reshape the array in other dimentions if you try to shrink size an array like say you have 10 elements you alloted 4 it will be value error
#if you give more then the required space it will throw a value error it must be perfect size to reshape the error
#if you use -1 like this example it will automatically reshape that dimention for the array
a.reshape(1,-1) #here reshape will decide the no of columns


a.ravel() #this is simimlar to that of an view in dbms and but it may modifiess the a in some cases be careful with it use this a.ravel(order = "F")
a.flatten() #this will return a copy of the array and will not effect teh original array it will be independent


np.transpose(a,axes=(1,3,2)) #here axes will change where the dimention is and aslo transpose the value 
#this is another transpose way
#if used on 1d array it will return reverse version
a.T

np.swapaxes(a,0,1) #this is used to swapp axes but not flip the entire thing easy management for 3d+ arrays
#this has the sytnax like this np.swapaxes(a,first,seconds)

np.reshape(a,(2,3)) #this will not be like reshape it is not necessary to be exact but if less you lose data if more then you have dupes
#this is not going to re arrange data like reshape to be viewd differently 

np.expand_dims(a,axis=0) #this will create a dimention before the first one 1 in between 1st and 2nd -1 for extending at the end
#similar to how a list works negtive indexing postive indexing we could use 0 1 2 3 for 4d ones 

np.squeeze(a,axis=0) #instead of adding a dim we remove one if any data we get error that dim must be empty to remove it 

In [ ]:
import numpy as np

#look picture these thing and its same ass python strings and lists
# basic 
a = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(a[1:3, 2:])  
# Output: [[6]
#          [9]]

#int indexing
a = np.array([[10, 20],
              [30, 40],
              [50, 60]])

print(a[[0, 1, 2], [1, 0, 1]])
# Output: [20 30 60]

#bool indexing

a = np.array([1, 2, 3, 4, 5])

print(a[a > 3])
# Output: [4 5]

mask = (a % 2 == 0)
print(a[mask])
# Output: [2 4]



#fancy indexing 
a = np.array([10, 20, 30, 40, 50])
idx = [1, 3, 4]

print(a[idx])
# Output: [20 40 50]

b = np.array([[1, 2], [3, 4]])
print(b[[0, 1], [1, 0]])
# Output: [2 3]


#combining sclicing and fancy indexing
a = np.arange(12).reshape(3, 4)
# array([[ 0,  1,  2,  3],
#        [ 4,  5,  6,  7],
#        [ 8,  9, 10, 11]])

print(a[1:3, [1, 3]])
# Output: [[ 5  7]
#          [ 9 11]]

[[232   7   8  32]
 [ 23   3  32  89]]
